### YamlMime:FAQ
metadata:
  title: よく寄せられるセキュリティの質問
  description: よく寄せられるセキュリティの質問と、HoloLens mixed reality デバイスに関する回答を確認してください。
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: 108f2e4c0aa9af251ecb6bc5185c7803ae51b5f7
  ms.sourcegitcommit: c43cd2f450b643ad4fc8e749235d03ec5aa3ffcf
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 07/12/2021
  ms.locfileid: "113637279"
title: HoloLens (第 1 世代) のセキュリティに関するよく寄せられる質問
summary: ''
sections:
- name: 無視
  questions:
  - question: >
      1 HoloLens のデータ保護のレベルを教えてください。
    answer: >
      * 「 [HoloLens (第1世代) BitLocker 暗号化](hololens1-encryption.md)」を参照してください。
  - question: >
      どのような種類のワイヤレスが使用されますか。
    answer: >
      * 802.11 ac および Bluetooth 4.1 LE
  - question: >
      どのような種類のアーキテクチャが組み込まれていますか。  例: point to point、メッシュなど。
    answer: >
      * Wi-Fi をインフラストラクチャモードで使用して、他のワイヤレスアクセスポイントと通信することができます。

      * Bluetooth を使用すると、顧客のアプリケーションでサポートされている場合、または他の Bluetooth デバイス HoloLens でピアツーピアと通信することができます。
  - question: >
      FCC ID とは
    answer: >
      * C3K1688
  - question: >
      デバイスが動作する頻度とチャネルはどのようなものですか。
    answer: >
      * Wi-fi: 頻度の範囲はユーザーが構成できないため、使用する国によって異なります。 米国 Wi-Fi では、2.4 GHz (1-11) チャネルと 5 GHz (36-64、100-165) チャネルの両方を使用します。

      * Bluetooth: Bluetooth は、標準 2.4-2.48 GHz の範囲を使用します。
  - question: >
      デバイスで特定の周波数を許可またはブロックできますか。
    answer: >
      * これは、ユーザー/デバイスが制御することはできません。
  - question: >
      送信と受信の両方の電源レベルはどのようなものですか。 調整はできますか。 操作の範囲は何ですか?
    answer: >
      * 排出のテスト標準については、 [こちら](https://fccid.io/C3K1688)を参照してください。 操作の範囲はアクセスポイントと環境に大きく依存しますが、その他の高品質の携帯電話、タブレット、または Pc とほぼ同じです。
  - question: >
      通常の運用では、デューティサイクル/有効期間はどのようなものですか?
    answer: >
      * 2-3 のアクティブな使用時間と最大2週間のスタンバイ時間

      * バッテリの有効期間は使用できません。
  - question: >
      ツールが範囲内にない場合の転送と受信の動作
    answer: >
      * HoloLens の送信/受信は、標準の wi-fi/Bluetooth パターンに従います。 範囲の端では、完全に切断されるまで入力が途切れることがありますが、その範囲に戻った後はすぐに再接続する必要があります。
  - question: >
      1平方フィートあたりのデプロイ密度とは
    answer: >
      * これは、ネットワークインフラストラクチャによって異なります。
  - question: >
      デバイスでクライアントとしてインフラストラクチャを使用できますか。
    answer: >
      * Yes
  - question: >
      使用されるプロトコル
    answer: >
      * HoloLens は独自のプロトコルを使用しません。
  - question: >
      OS 更新頻度– HL の OS 更新プログラムの頻度はどのくらいですか。  スケジュールが設定されていますか?  Microsoft は、必要に応じてセキュリティ修正プログラムをリリースします。
    answer: >
      * Microsoft は、Windows 10 の場合とまったく同じ方法で、OS の更新プログラムを HoloLens 提供します。 通常、1年あたり2つの主要な更新プログラムがあります。1つは spring で、1つは秋です。 HoloLens が Windows デバイスであるため、更新の概念は他の Windows デバイスと同じです。 Microsoft は、必要に応じてセキュリティ修正プログラムをリリースし、他の Windows デバイスで実行されるのと同じ概念に従います。
  - question: >
      OS のセキュリティ強化– OS を強化するためにどのようなオプションがありますか。  不要なアプリやサービスを削除またはシャットダウンすることはできますか。
    answer: >
      * HoloLens はスマートフォンのように動作します。 これは、他の最新の Windows デバイスと同等です。 HoloLens は、Microsoft Intune または mobileiron、放映 watch、soti などの最新のデバイス管理ソリューションで管理できます。 これらの管理システムでは、デバイスにセキュリティポリシーを設定し、デバイスを強化するために設定できるポリシーがあります。 必要に応じて、不要なアプリケーションを削除するオプションもあります。
  - question: >
      ソフトウェアアプリケーションはどのように管理および更新されますか。 どのようなコントロールを使用して、どのアプリを読み込むか、および Microsoft store に住むアプリのアプリの更新プロセスを定義する必要がありますか。
    answer: >
      * HoloLens は、Windows ストアを介してのみソフトウェアアプリケーションを取得します。 HoloLens を使用するために開発された、Appx アプリケーションパッケージのみをインストールできます。 これは、HoloLens デバイスを表示するアプリケーションの横にある小さなロゴを使用して、Microsoft Store で確認できます。 ストアアプリケーションの管理上にあるすべてのコントロールは、HoloLens にも適用されます。 公式ストアまたはビジネス向けストアの概念を使用できます。 アプリは、サイドロードする (手動プロセスで Windows デバイスにアプリを読み込む) ことができます。また、必要に応じてアプリがストアから自動的にプルされるように、MDM を通じて管理することもできます。
  - question: >
      HoloLens ストアのアプリに対する更新の頻度はどのくらいですか?
    answer: >
      * Microsoft Store と同じ概念に従い、そこからアプリをプルするため、更新サイクルはアプリケーションの開発者によって決定されます。 ストアの更新メカニズムを制御する必要があるすべての管理オプションも HoloLens に適用されます。
  - question: >
      HoloLens に対してセキュアブート機能はありますか。
    answer: >
      * Yes
  - question: >
      デバイスから周辺機器のサポートを無効にしたり切断したりする機能はありますか。
    answer: >
      * Yes
  - question: >
      デバイスでポートの使用を制御または無効化する機能はありますか。
    answer: >
      * HoloLens には、2つのポートが含まれています (1 つはヘッドフォン用で、もう1つは pc に接続するためのポートです)。 機能と回復の理由により、ポートを無効にすることはできません。
  - question: >
      ウイルス対策、エンドポイント検出、IP、アプリ制御許可リスト–ウイルス対策、エンドポイント検出、IP、アプリ制御許可リストなどを実行する機能。
    answer: >
      * Windows Holographic for Business (商用 suite) は Windows Defender スマートスクリーンをサポートしています。 ウイルス対策会社がユニバーサル Windows プラットフォームにアプリを作成して発行する場合は、HoloLens でダウンロードできます。 現時点では、どの企業も HoloLens に対してこれを行っていません。

      * Microsoft Enterprise ストアを使用してアプリを許可することができます。ここでは、ダウンロードできる特定のアプリのみを選択できます。 また、MDM を通じて、デバイスで実行できる特定のアプリや、デバイスで確認できるアプリをロックできます。
  - question: >
      長時間にわたってオフラインになっているデバイスを更新するまで、運用ネットワークからデバイスを検疫することはできますか。  例: デバイスが、1時間 (6 か月) の電源を入れず、更新プログラムや修正プログラムなどを受け取っていないドロアーに入っています。 ネットワークに接続しようとすると、にフラグを付けることができます。ネットワークに参加する前に、別のネットワーク上で更新する必要があります。
    answer: >
      * これは、MDM またはオンプレミスのサーバーのいずれかによってインフラストラクチャレベルで管理できるものです。 デバイスは、指定された更新プログラムのバージョンを満たしていない場合、非準拠としてフラグを設定できます。
  - question: >
      Microsoft には、Microsoft がデバイスに接続して画面の共有やリモートサポートを行うことができるようにするためのバックドアまたはサービスへのアクセスが含まれていますか。
    answer: >
      * No
  - question: >
      信頼された通信用に PKI 証明書を生成する場合は、デバイス上で証明書を生成し、そのデバイスに固有のものであることを確認し、デバイスの権限を借用するためにエクスポートまたは使用することはできません。 これは HoloLens に当てはまりますか。 そうでない場合は、軽減策がありますか。
    answer: >-
      * SCEP の CSR は、デバイス自体に生成されます。 Intune とオンプレミスの SCEP コネクタを使用すると、クライアントに送信されるチャレンジ文字列を追加して検証することで、要求自体をセキュリティで保護することができます。

      * HoloLens (第1世代と第2世代) には tpm モジュールがあるため、これらの証明書は tpm モジュールに格納され、抽出することはできません。 さらに、抽出できたとしても、別のデバイスではチャレンジ文字列を検証できませんでした。証明書/キーを別のデバイスで使用することはできません。
